# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx690tffg1761-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.cache/wt [current_project]
set_property parent.project_path /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  /home/hassan/Documents/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.ip_user_files/mem_init_files/llrs_input_sfix10_En4_frame0.mem
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/llrs_input_sfix10_En4.mem
}
read_verilog -library xil_defaultlib {
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/lib/axis/rtl/arbiter.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/arp.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/arp_cache.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/arp_eth_rx.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/arp_eth_tx.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/lib/axis/rtl/axis_async_fifo.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/lib/axis/rtl/axis_async_fifo_adapter.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/lib/axis/rtl/axis_fifo.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/axis_xgmii_rx_64.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/axis_xgmii_tx_64.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/rtl/debounce_switch.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/eth_arb_mux.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/eth_axis_rx.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/eth_axis_tx.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/eth_mac_10g.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/eth_mac_10g_fifo.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/rtl/fpga_core.v
  /home/hassan/Documents/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.srcs/sources_1/new/hdl_algorithm_wrapper.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/rtl/i2c_master.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/ip_64.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/ip_arb_mux.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/ip_complete_64.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/ip_eth_rx_64.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/ip_eth_tx_64.v
  /home/hassan/Documents/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.srcs/sources_1/new/ldpc_output_serializer.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/lfsr.v
  /home/hassan/Documents/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.srcs/sources_1/new/llr_input_controller.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/lib/axis/rtl/priority_encoder.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/rtl/si5324_i2c_init.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/lib/axis/rtl/sync_reset.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/udp_64.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/udp_checksum_gen_64.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/udp_complete_64.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/udp_ip_rx_64.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/rtl/udp_ip_tx_64.v
  /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/rtl/fpga.v
}
read_vhdl -library xil_defaultlib {
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/HDL_Algorithm_pkg.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/AposterioriUnit.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/BarrelRotator.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/BetaCalculationUnit.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/BetaDecompress.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/FinalShifts.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/CheckMatrixLUT.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/SimpleDualPortRAM_generic.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/CheckNodeRAM.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/CheckNodeUnit.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/CodeParameters.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/SerialCircularShifter.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/VariableNodeUnit.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/FunctionalUnit.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/MetricCalculator.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/FinalDecision.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/DecoderCore.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/NR_LDPC_Decoder.vhd
  /home/hassan/snap/snapd-desktop-integration/253/Desktop/NRLDPCDecoderHDL/HDL_Algorithm.vhd
}
read_ip -quiet /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/ten_gig_eth_pcs_pma_0.xci
set_property used_in_implementation false [get_files -all /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/synth/ten_gig_eth_pcs_pma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/synth/ten_gig_eth_pcs_pma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/synth/ten_gig_eth_pcs_pma_0.xdc]

read_ip -quiet /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.srcs/sources_1/ip/ten_gig_eth_pcs_pma_1/ten_gig_eth_pcs_pma_1.xci
set_property used_in_implementation false [get_files -all /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.srcs/sources_1/ip/ten_gig_eth_pcs_pma_1/synth/ten_gig_eth_pcs_pma_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.srcs/sources_1/ip/ten_gig_eth_pcs_pma_1/synth/ten_gig_eth_pcs_pma_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga/fpga.srcs/sources_1/ip/ten_gig_eth_pcs_pma_1/synth/ten_gig_eth_pcs_pma_1.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga.xdc
set_property used_in_implementation false [get_files /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/fpga.xdc]

read_xdc -unmanaged /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/syn/vivado/eth_mac_fifo.tcl
set_property used_in_implementation false [get_files /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/syn/vivado/eth_mac_fifo.tcl]

read_xdc -unmanaged /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/lib/axis/syn/vivado/axis_async_fifo.tcl
set_property used_in_implementation false [get_files /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/lib/axis/syn/vivado/axis_async_fifo.tcl]

read_xdc -unmanaged /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/lib/axis/syn/vivado/sync_reset.tcl
set_property used_in_implementation false [get_files /home/hassan/Downloads/verilog-ethernet/example/NetFPGA_SUME/fpga/lib/eth/lib/axis/syn/vivado/sync_reset.tcl]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top fpga -part xc7vx690tffg1761-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_utilization_synth.rpt -pb fpga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
